name: Speller
version: ${project.version}
main: me.marcarrots.speller.Speller
api-version: 1.16
authors: [ MarCarrot ]
commands:
  spell:
    description: "Main command."
  spell-undo:
    description: "Undo stuff."
  spell-redo:
    description: "Redo stuff."